### ISSUE TITLE
[Bug] Failed to import games from RomM. Can not convert Null to UInt64

### ISSUE THREAD

**Issue by Casuallynoted** [rommapp/playnite-plugin#11]
**Describe the bug**
At the moment, when I try to add my Romm library to playnite, it throws this error after the "update library" step. I have gone ahead and set the settings for the integration as per the guide and will include a screenshot of my settings (minus the host, username, and password)

![image](https://github.com/rommapp/playnite-plugin/assets/6272557/924418a4-409d-4f17-ad90-891cfb7931c5)

**Comment by gantoine** [comment]
Could you post the contents of `playnite.log`, either the full thing, or sift through it and find the error?

**Comment by Casuallynoted** [comment]
> Could you post the contents of `playnite.log`, either the full thing, or sift through it and find the error?

Absolutely, this is the error in my playnite log!

03-04 14:53:24.820|ERROR|MainViewModelBase:Failed to import games from plugin: RomM
System.ArgumentException: Can not convert Null to UInt64.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at RomM.RomM.<>c__DisplayClass33_0.<GetGames>b__1(JToken p)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at RomM.RomM.<GetGames>d__33.MoveNext()
   at Playnite.Database.GameDatabase.ImportGames(LibraryPlugin library, CancellationToken cancelToken, PlaytimeImportMode playtimeImportMode) in C:\projects\playnite\source\Playnite\Database\GameDatabase.cs:line 1223
   at Playnite.ViewModels.MainViewModelBase.ImportLibraryGames(LibraryPlugin plugin, CancellationToken token) in C:\projects\playnite\source\Playnite\ViewModels\MainViewModelBase.cs:line 506
03-04 14:53:24.820|INFO |MainViewModelBase:Starting Library Install Size scan
03-04 14:53:24.820|INFO |MainViewModelBase:Finished Library Install Size scan
03-04 14:53:25.836|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 11994869-fc24-4073-947f-7e4965b54cc9
03-04 14:53:25.862|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 11994869-fc24-4073-947f-7e4965b54cc9, True

**Comment by gantoine** [comment]
Ok I think I see the issue, like with this line: `{ "platform_id", apiPlatforms.FirstOrDefault(p => p["igdb_id"].ToObject<ulong>() == mapping.Platform.IgdbId)["id"].ToString() }`

There's a platform with no IGDB ID, which is throwing an error on sync. I'll fix this in a patch release!

**Comment by gantoine** [comment]
Should be fixed in the latest release!

**Comment by Casuallynoted** [comment]
I did just update the add-on, but unfortunately it does still seem to be happening- Including log excerpt:


05-04 17:58:43.838|ERROR|MainViewModelBase:Failed to import games from plugin: RomM
System.ArgumentException: Can not convert Null to UInt64.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at RomM.RomM.<>c__DisplayClass33_0.<GetGames>b__1(JToken p)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at RomM.RomM.<GetGames>d__33.MoveNext()
   at Playnite.Database.GameDatabase.ImportGames(LibraryPlugin library, CancellationToken cancelToken, PlaytimeImportMode playtimeImportMode) in C:\projects\playnite\source\Playnite\Database\GameDatabase.cs:line 1223
   at Playnite.ViewModels.MainViewModelBase.ImportLibraryGames(LibraryPlugin plugin, CancellationToken token) in C:\projects\playnite\source\Playnite\ViewModels\MainViewModelBase.cs:line 506

**Comment by gantoine** [comment]
Of the platforms you've configured, so all of them have an IGDB ID in RomM? That is, do any have a warning icon next to them in the sidebar?

**Comment by Casuallynoted** [comment]
> Of the platforms you've configured, so all of them have an IGDB ID in RomM? That is, do any have a warning icon next to them in the sidebar?

All of them do, I've also tried disabling all but one platform (done this with multiple platforms) and it still throws the error

**Comment by gantoine** [comment]
Could you uninstall it in playnite, then download it from the releases page https://github.com/rommapp/playnite-plugin/releases/tag/v0.2.2 and install it? You can drag-drop the .pext file into playnite.

**Comment by Casuallynoted** [comment]
Sadly no change after uninstalling and manually installing from releases

**Comment by gantoine** [comment]
Ok I sent ya a debug build on Discord to try
